### ISSUE TITLE
Create Appkit adapter

### ISSUE THREAD

**Issue by vittominacori** [luu-alex/web3js-web3modal#1]
Is there any possibility to create a web3js appkit adapter?

**Comment by luu-alex** [comment]
Hey There @vittominacori its possible, whats the purpose? is that a library you are using?

**Comment by vittominacori** [comment]
Yes, I'm using web3js with web3modal and would like to upgrade to the new appkit library.

**Comment by vittominacori** [comment]
Migrated to reown/appkit.
